; Generated by AutoGUI 1.3.3a
#NoEnv
#Warn
#SingleInstance Force
; SetWorkingDir %A_ScriptDir%
; global Elength, Ewidth, Eheight

getVolume(){
	Gui, Add, Edit, vElength w40 hwndl 
	Gui, Add, Edit, YS vEwidth w40 hwndw 
	Gui, Add, Edit, YS vEheight w40 hwndh 
	Gui Add, Button, Default YS, &Submit
	; return 
	Gui Show


	GuiEscape:
	GuiClose:
	    ExitApp


	ButtonSubmit:
	Gui, Submit
	SetFormat, float, 0.1
	return Elength*Ewidth*Eheight/2
	ExitApp
}
	
; Do not edit above this line
; Do not edit above this line